### ISSUE TITLE
RStudio integration wit Galaxy

### ISSUE THREAD

**Issue by marijazmf** [erasche/docker-rstudio-notebook#16]
Hi,

I am working on integration of Jupyter and RStudio into Galaxy (IE). I menage to integrate Jupyter and it works very well. I am having issues with RStudio. 
Is there any "step-by-step" description for the integration?
My log file:
```
galaxy.web.base.interactive_environments INFO 2016-08-05 14:53:50,963 Starting docker container for IE rstudio with command [docker run --sig-proxy=true -e DEBUG=true -e DEFAULT_CONTAINER_RUNTIME=120 -e "GALAXY_URL=https://galaxy.medunigraz.at" -e "NOTEBOOK_USERNAME=galaxy" -e "CORS_ORIGIN=https://galaxy.medunigraz.at" -e "GALAXY_WEB_PORT=None" -e "HISTORY_ID=606f7a6aa0323b9d" -e "NOTEBOOK_PASSWORD=utb7y6j3fpfroph4s4yr06m0" -e "PROXY_PREFIX=/gie_proxy/rstudio" -e "API_KEY=b27201ca5ac4cc7e469c77f13ad05b91" -e "REMOTE_HOST=10.200.168.222" -e "USER_EMAIL=marija.durdevic@medunigraz.at" -d -P -v "/home/data/galaxy_database/tmp/tmpBRM1ww:/import/"  erasche/docker-rstudio-notebook:16.01]
galaxy.web.base.interactive_environments ERROR 2016-08-05 14:53:51,734 99e0fa097795cd3d9d7ddc6e004f9a0de0b59d18dc9739665830e1756d3dc273

docker: Error response from daemon: oci runtime error: permission denied.

galaxy.webapps.galaxy.controllers.visualization ERROR 2016-08-05 14:53:51,734 error rendering visualization (rstudio): 'Bunch' object has no attribute 'proxy_url'
Traceback (most recent call last):
```

Any suggestion what can be wrong?

Thanks in advance.

Regards,
Marija

**Comment by erasche** [comment]
Hi @marijazmf,

This image is currently a little bit out of date, but @nturaga has some updates to the image that are likely to get it working again. I believe he will make a pull request soon, and then that might fix your issue. With the updates, it should be just as simple to integrate as the Jupyter notebook is.

**Comment by erasche** [comment]
Side note, I have not seen "oci runtime error" before, that's quite odd.

**Comment by marijazmf** [comment]
Dear Eric,
Thank you very much for quick response. Good look with image updates. I am looking forward to use it soon.
Regards,
Marija
