### ISSUE TITLE
Extract GalaxyConnector scripts in a dedicated repository

### ISSUE THREAD

**Issue by lecorguille** [erasche/docker-rstudio-notebook#22]
Hi @erasche ,

We are wondering with @RomainDallet, if you can extract the GalaxyConnector scripts and push them in a dedicated GitHub repositiory?
Because, currently, in our [gie-shiny](https://github.com/workflow4metabolomics/gie-shiny), they are included "manually". And it should be great, if we could include a git submodule or download them directly in the image as we did for [galaxy_ie_helpers](https://github.com/workflow4metabolomics/gie-shiny/blob/master/Dockerfile#L32)

What do you think about that?

Cheers

**Comment by erasche** [comment]
No problem! That's easily done.

**Comment by erasche** [comment]
https://github.com/erasche/rGalaxyConnector enjoy.

**Comment by lecorguille** [comment]
Thanks @erasche
