### ISSUE TITLE
Many /monitor_traffic.sh processes after user has left

### ISSUE THREAD

**Issue by abretaud** [erasche/docker-rstudio-notebook#25]
Opening an issue for now as I don't have much time to debug more
Today I discovered >6000 /monitor_traffic.sh processes were running on the server where rstudio GIE are launched. I had to kill the rstudio container that was running since yesterday.
I think the problem is that:
- The user launches the rstudio GIE, and everything goes well
- Then he leaves, and monitor_traffic should see it and kill the container somehow
- It doesn't get killed, and every 4 minutes, a new monitor_traffic.sh is launched, while `rm: cannot remove '/import/': Device or resource busy` appears in the container log

So I guess we should change [this line](https://github.com/erasche/docker-rstudio-notebook/blob/19.05/monitor_traffic.sh#L21), but I haven't tested yet

**Comment by erasche** [comment]
Woooow that's horrifying

**Comment by abretaud** [comment]
Made a few tests, the "cannot remove" error is not the cause of the error, it's just that killing nginx doesn't kill the docker. I think I'll have a fix soon.
